#
#
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

def triangle(number):
    list = [1]
    index = 1 #or 0?
    for i in range(1,number):
        index += 1
        list.append(index)
    return list

# print(triangle(7))

def sum_triangle(number2):
    l = triangle(number2)
    l2 = []
    sum = 1
    for j in range(1,number2):
        l2.append(sum)
        sum += l[j]
    return l2

# sum_triangle(10000)



for i in sum_triangle(1000):
    n = 2
    som = 0
    for k in range(1,i):
        if i%k == 0:
            som += 1
            if som == 10:
                print(i,k, som)
                break
        som = 0



